version: '3'

services:
  api:
    restart: always
    build: ./backend
    command: "python wsgi.py"
    ports:
      - "5000:5000"

  client:
    restart: always
    build: ./frontend
    command: "npm start"
    volumes:
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  node-modules: